### ISSUE TITLE
Unable install rpy2 on windows 10

### ISSUE THREAD

**Issue by pgasperowicz** [rpy2/rpy2#1044]
Just cant make it work. Any ideas?

- Windows 10 Pro
- R version: 4.3.1
- R_HOME=C:\Program Files\R\R-4.3.1 (verified by calling os.environ["R_HOME"])

- PATH=...;
        C:\Program Files\R\R-4.3.1;
        C:\Program Files\R\R-4.3.1\bin;
        C:\Program Files\R\R-4.3.1\bin\x64;
        ...;

- pyenv 3.1.1
- Python: 3.11 installed by pyenv as global version
- pip updated (23.1.2), wheel (0.38.4) and setuptools (65.5.0) are installed
- Visual studio community 2022, v17.6.4 (all updates installed)

Error:
```
Collecting rpy2
  Using cached rpy2-3.5.13.tar.gz (218 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      test_pw_r.c
      LINK : fatal error LNK1181: cannot open input file 'R.lib'
      Traceback (most recent call last):
        File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-bqc4bpw5\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 508, in link
          self.spawn([self.linker] + ld_args)
        File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-bqc4bpw5\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 517, in spawn
          return super().spawn(cmd, env=env)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-bqc4bpw5\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-bqc4bpw5\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\{user}\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\{user}\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\{user}\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-bqc4bpw5\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-bqc4bpw5\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-bqc4bpw5\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 124, in <module>
        File "<string>", line 118, in get_r_c_extension_status
        File "<string>", line 81, in get_c_extension_status
        File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-bqc4bpw5\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 781, in link_executable
          self.link(
        File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-bqc4bpw5\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 510, in link
          raise LinkError(msg)
      distutils.errors.LinkError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
EDIT:
Error also occurs when calling: `pip install rpy2 --no-cache-dir`

**Comment by zittirone** [comment]
I have exactly the same behavior. I am working with R. 4.3.2 and Pyhton3.9 under Windows 10. R_HOME is set and Python and R are part of PATH environment variable

**Comment by zittirone** [comment]
Ok I found the following solution in https://stackoverflow.com/questions/71009659/message-note-this-error-originates-from-a-subprocess-and-is-likely-not-a-prob:
33

"I had Python 3.10 and had the same error installing psutil from pip. I fixed the problem by installing an older version of pip using the command:
pip install pip==21.3.1" downgrading pip did the job for me.

**Comment by pgasperowicz** [comment]
Good call! I downgraded pip 21.3.1 as you sugested. But simple command `poetry update rpy2` didnt work. 
I was able to install rpy2 by calling: `poetry run pip install rpy2 --force-reinstall --no-cache-dir`

At the very beggining same error was thrown but then it was omitted and installation succeded

```
Collecting rpy2
  Downloading rpy2-3.5.13.tar.gz (218 kB)
     |████████████████████████████████| 218 kB 3.3 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\Dokumenty\Python\zgm-app\.venv\Scripts\python.exe' 'D:\Dokumenty\Python\zgm-app\.venv\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\{user}\AppData\Local\Temp\tmpmxdml3pk'
       cwd: C:\Users\{user}\AppData\Local\Temp\pip-install-c6mxjm9o\rpy2_63d8d4689745413c9c1f09ce677f5416
  Complete output (40 lines):
  test_pw_r.c
  LINK : fatal error LNK1181: cannot open input file 'R.lib'
  Traceback (most recent call last):
    File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-r52mwaas\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 508, in link
      self.spawn([self.linker] + ld_args)
    File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-r52mwaas\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 517, in spawn
      return super().spawn(cmd, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-r52mwaas\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 1041, in spawn
      spawn(cmd, dry_run=self.dry_run, **kwargs)
    File "C:\Users\{user}\AppData\Local\Temp\pip-build-env-r52mwaas\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 70, in spawn
      raise DistutilsExecError(
  distutils.errors.DistutilsExecError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/55/43/d11bbc1e87383e8a01d74022182bc292011760a2f23c449d2c04dc1b794e/rpy2-3.5.13.tar.gz#sha256=41d037599f54336f54e754d82853fae06be9438d9fb3b514d90da74eaf328ddd (from https://pypi.org/simple/rpy2/) (requires-python:>=3.7). 
Command errored out with exit status 1: 'D:\{path}\.venv\Scripts\python.exe' 'D:\{path}\.venv\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\{user}\AppData\Local\Temp\tmpmxdml3pk' 
Check the logs for full command output.
  ...

Successfully built rpy2
Installing collected packages: tzdata, pytz-deprecation-shim, pycparser, MarkupSafe, tzlocal, pytz, packaging, jinja2, cffi, rpy2
  ...

Successfully installed MarkupSafe-2.1.3 cffi-1.15.1 jinja2-3.1.2 packaging-23.1 pycparser-2.21 pytz-2023.3 pytz-deprecation-shim-0.1.0.post0 rpy2-3.5.12 tzdata-2023.3 tzlocal-4.3.1

```

**Comment by paulmueller** [comment]
@pgasperowicz Your solution of downgrading pip is effectively just downgrading rpy2 to version 3.5.12. For the latest version of rpy2, installation on Windows still fails.

-> Reopen this issue?
