### ISSUE TITLE
rpy2 letting R handle a segfault. 

### ISSUE THREAD

**Issue by ocschwar** [rpy2/rpy2#707]
I have a Python process that uses Rpy2 to babysit an R process that in turn calls a C library. That library has a known tendency to generate segfaults. Unfortunately, without some configuration on my part, the details of which I am desperately trying to trawl SO/Google/here et cetera, what happens is that the R process offers Rpy2 this dialogue, at which point Rpy2 gets into an infinite loop:

` *** caught segfault ***
address 0x3e90000291f, cause 'unknown'

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 
`

How do I tell Rpy2 to tell R not to do this? I just want to detect the issue one way or another, log it and move on, on the Python side of this abstraction.

**Comment by lgautier** [comment]
The menu you are showing is R's own menu when trying to make a graceful exit.

The infinite loop you are experiencing is possibly a bug on the rpy2 side (do you mean that entering a selection results in the same question menu with no end is sight ?).

Otherwise, here are what the 4 options would do:
- 1: sudden termination of the Python process in which rpy2 is running (more on this below)
- 2: the Python process in which rpy2 is (was) running continues but it will no longer be able to use an embedded R / rpy2
- 3: see 2) above
- 4: see 2) above

If you want to recover from this enough to be able to keep using R, the only way will be to have rpy2 running in in a different process (like a child process, for example managed using `multiprocessing`).

**Comment by ocschwar** [comment]
I'd just like rpy2 to not get into an infinite loop in this situation, and throw an exception. (RRuntimeError ?)
Then I can recover from the situation on the Python side instead of wondering why my processes are not completing.

**Comment by lgautier** [comment]
The infinite loop is a bug, likely coming from an issue with the callback that handle's R input for 1, 2, 3, or 4.

Otherwise, exiting an embedded R will leave you unable to restart R.

**Comment by lgautier** [comment]
The fix for the issue with the broken input in the main branch and in `v3.3.x`. The fix will be included with release 3.3.5.

**Comment by lgautier** [comment]
rpy2-3.3.5 is out. I do not have a test that makes R crash readily available but the handling of the crash menu (that it answering 1, 2, 3,or 4). Should be fixed. Reopen the issue if not the case.

**Comment by ocschwar** [comment]
Upgraded. Many thanks!

**Comment by ocschwar** [comment]
Sorry, but the issue persists. `
"2020-07-10 00:55:33" - rpy2.rinterface_lib.callbacks - WARNING - R[write to console]: 
Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

"2020-07-10 00:55:33" - rpy2.rinterface_lib.callbacks - ERROR - R[read into console]: EOF when reading a line
`

**Comment by ocschwar** [comment]
And I cannot reopen the ticket.

**Comment by lgautier** [comment]
I thought the author of the issue could reopen it.

**Comment by lgautier** [comment]
Does last error occur before or after you press 1, 2, 3, or 4 ?

**Comment by lgautier** [comment]
Otherwise, walling Python's `input()` function when there is nothing to read from. For example:

```bash
$ echo '1' | python -c 'input(); input()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
EOFError: EOF when reading a line
```

Without a good way to reliably trigger R crashes it is hard to investigate this.
Could you verify this with a simple custom alternative callback? (for example with debug prints)
The doc is here:
https://rpy2.github.io/doc/v3.3.x/html/callbacks.html#read-console
